runtime: python39
entrypoint: gunicorn -b :$PORT flaskr:create_app() --workers 1 --threads 1

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1

env_variables:
  SECRET_KEY: "your_production_secret_key"
